---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  # remote_user: root
  # remote_user: user
  become: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
