---
# This playbook contains common plays that will be run on all nodes.

# - name: yum-clean-metadata
#  command: yum clean metadata
#  args:
#    warn: no

- name: Ansible remove file
  file:
    path: "/etc/yum.repos.d/cd.repo"
    state: absent

- name: Installer l'agent Katello
  yum:
    disable_gpg_check: yes
    name: "{{ katello_path }}"
    state: present

- name: Enregistrement a Satellite avec la cle d'activation
  redhat_subscription:
    state: present
    activationkey: "{{ var_activationkey }}"
    org_id: "{{ var_org_id }}"
  ignore_errors: True
    
- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Install common dependencies
  yum: name={{ item }} state=installed
  with_items:
   - libselinux-python
   - libsemanage-python
   - firewalld

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp
